version: 2
jobs:
  build:
    working_directory: /xml-validator
    docker:
      - image: julia:0.7
    steps:
      - checkout
      - run:
          name: install the LightXML package
          command: julia -e 'using Pkg; Pkg.add("LightXML");'
      - run:
          name: Test files in dir
          command: julia tests.jl 
      - run:
          name: Setup test_dir env variable
          command: echo 'export TEST_DIR="./test_data"' >> "$BASH_ENV"
      - run:
          name: Run test 1, ok
          command: julia xml-validate.jl ${TEST_DIR}/shiporder.xml ${TEST_DIR}/shiporder.xsd
      - run:
          name: Run test 2, ok
          command: julia xml-validate.jl  ${TEST_DIR}/configuration.xml ${TEST_DIR}/configuration.xsd
      - run:
          name: Run test 3, fail
          command: julia xml-validate.jl  ${TEST_DIR}/configuration_nonvalid.xml ${TEST_DIR}/configuration.xsd || true
      - run:
          name: Run test 4, fail
          command: julia xml-validate.jl ${TEST_DIR}/shiporder_nonvalid.xml ${TEST_DIR}/shiporder.xsd || true
