version: 2
jobs:
  build:
    working_directory: /xml-validator
    docker:
      - image: julia:0.7
    steps:
      - checkout
      - run:
          name: install the LightXML package
          command: julia -e 'using Pkg; Pkg.add("LightXML");'
      - run:
          name: Test files in dir
          command: julia tests.jl 
      - run:
          name: Run test 1
          command: julia xml-validate.jl ./test_data/shiporder.xml ./test_data/shiporder.xsd
      - run:
          name: Run test 2
          command: julia xml-validate.jl  ./test_data/configuration.xml ./test_data/configuration.xsd
